// page_to_build.mjs — reconstruct an OWNING build script from a live page's draft state.
// For pages with no build script (task qa-build-scripts-migration.md): dumps the page's
// draft_section_groups + draft_sections (+ page-level filters/sidebar) and emits a runnable,
// idempotent build script in the established idiom (find-by-slug, wipe by PAGE ID with loud
// failures, recreate sections in order). Exported content is VERBATIM — hand-fixes made on the
// live page are captured.
//
//   DMS_AUTH_TOKEN=… node src/themes/transportny/qa_skills/tools/page_to_build.mjs \
//     --pattern tsmo2 --slug about \
//     [--out src/themes/transportny/qa_skills/tools/builds/build_tsmo2_about.mjs]
//
// Fidelity gate (do BOTH before adopting the script as owner):
//   1. run the generated script → "built N sections" must equal the exported N; page renders.
//   2. re-export and diff against the first export (section ids aside, content identical).
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const argv = process.argv.slice(2);
const opt = (n, d) => { const i = argv.indexOf(`--${n}`); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
const PATTERN = opt("pattern"), SLUG = opt("slug");
if (!PATTERN || !SLUG) { console.error("--pattern and --slug required"); process.exit(1); }
const OUT = opt("out", `src/themes/transportny/qa_skills/tools/builds/build_${PATTERN}_${SLUG.replace(/\W+/g, "_")}.mjs`);

const ENV = { ...process.env, DMS_HOST: process.env.DMS_HOST || "http://localhost:3001", DMS_APP: process.env.DMS_APP || "npmrdsv5", DMS_TYPE: process.env.DMS_TYPE || "dev2" };
const cli = (...a) => execFileSync("node", ["src/dms/packages/dms/cli/bin/dms.js", ...a], { env: ENV, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
const clean = (s) => s.split("\n").filter((l) => l.trim().startsWith("{") || l.trim().startsWith("[")).pop();
const jget = (id) => JSON.parse(clean(cli("raw", "get", String(id))));

// find the page
const listOut = cli("page", "list", "--pattern", PATTERN);
const items = (JSON.parse(clean(listOut)).items || JSON.parse(clean(listOut))) || [];
const page = items.find((p) => (p.url_slug || p.data?.url_slug) === SLUG);
if (!page) { console.error(`no page with slug '${SLUG}' in pattern '${PATTERN}'`); process.exit(1); }
const pageRow = jget(page.id);
const d = pageRow.data;

// page-level attributes the build must own (identity/state fields excluded)
const PAGE_ATTR_KEYS = ["filters", "sidebar", "navOptions"];
const pageAttrs = {};
for (const k of PAGE_ATTR_KEYS) if (d[k] !== undefined && d[k] !== null) pageAttrs[k] = d[k];

const groups = d.draft_section_groups || [];
const refs = d.draft_sections || [];
const SERVER_KEYS = new Set(["createdAt", "updatedAt", "created_at", "updated_at"]);
const sections = refs.map((r) => {
  const row = jget(r.id);
  const data = {};
  for (const [k, v] of Object.entries(row.data || {})) if (!SERVER_KEYS.has(k)) data[k] = v;
  return data;
});
console.error(`exported ${groups.length} groups, ${sections.length} sections, pageAttrs: [${Object.keys(pageAttrs).join(", ")}]`);

const script = `// build_${PATTERN}_${SLUG.replace(/\W+/g, "_")}.mjs — OWNING build for ${PATTERN}/${SLUG} (page ${page.id}).
// AUTO-GENERATED by page_to_build.mjs on ${new Date().toISOString().slice(0, 10)} from the live draft state
// (verbatim content-as-code; hand-fixes up to that date are captured). Maintain by EDITING the
// SECTIONS payloads below and re-running — idempotent: wipes by PAGE ID (loud) and recreates.
// Run from dms-template root with DMS_AUTH_TOKEN set. Draft-only: never publishes.
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PATTERN = ${JSON.stringify(PATTERN)}, SLUG = ${JSON.stringify(SLUG)};
const ENV = { ...process.env, DMS_HOST: process.env.DMS_HOST || "http://localhost:3001", DMS_APP: process.env.DMS_APP || "npmrdsv5", DMS_TYPE: process.env.DMS_TYPE || "dev2" };
const cli = (...a) => execFileSync("node", ["src/dms/packages/dms/cli/bin/dms.js", ...a], { env: ENV, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
const clean = (s) => s.split("\\n").filter((l) => l.trim().startsWith("{") || l.trim().startsWith("[")).pop();

const GROUPS = ${JSON.stringify(groups, null, 1)};

const PAGE_ATTRS = ${JSON.stringify(pageAttrs, null, 1)};

const SECTIONS = ${JSON.stringify(sections, null, 1)};

// ── apply (find-or-create by slug · wipe by PAGE ID, loud · recreate in order) ──
const out = cli("page", "list", "--pattern", PATTERN);
const items = (JSON.parse(clean(out)).items || JSON.parse(clean(out))) || [];
let pageId = items.find((p) => (p.url_slug || p.data?.url_slug) === SLUG)?.id;
if (!pageId) { pageId = (cli("page", "create", "--pattern", PATTERN, "--title", SLUG, "--slug", SLUG).match(/"id"\\s*:\\s*"?(\\d+)"?/) || [])[1]; console.log("created", SLUG, pageId); }
else console.log("reusing", SLUG, pageId);
const existing = JSON.parse(clean(cli("raw", "get", String(pageId)))).data.draft_sections || [];
for (const e of existing) {
  try { cli("section", "delete", String(e.id), "--page", String(pageId)); }
  catch (err) { console.log("  DELETE FAILED for", e.id, String(err).slice(0, 120)); }
}
console.log("wiped", existing.length, "sections");
cli("raw", "update", String(pageId), "--data", JSON.stringify({ draft_section_groups: GROUPS, ...PAGE_ATTRS }));
// payloads go via temp FILES (\`--data <path>\`) — big sections (map symbology) exceed argv limits
const tmp = mkdtempSync(join(tmpdir(), "build_sections_"));
try {
  SECTIONS.forEach((s, i) => {
    const f = join(tmp, \`s\${i}.json\`);
    writeFileSync(f, JSON.stringify(s));
    cli("section", "create", String(pageId), "--pattern", PATTERN, "--data", f);
  });
} finally { rmSync(tmp, { recursive: true, force: true }); }
console.log(\`built \${SECTIONS.length} sections on /\${SLUG} (\${pageId})\`);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, script);
console.log(OUT);
