/**
 * FORKED FROM map21 on 2026-08-14 — see
 * planning/transportny/tasks/current/pm3-fork-and-measure-implementation.md (Phase 0).
 *
 * pm3 and map21 are deliberately allowed to diverge from here: map21 is frozen for
 * calculation (federal submittal, backward compatibility), pm3 is not. Do NOT
 * "resync" this file with ../../map21/constants.js — divergence is the point.
 * pm3/tests/no-map21-import.unit.test.mjs enforces that pm3 never imports map21 again.
 */
const NPMRDS_CH_SCHEMA_NAME = 'npmrds';

const ALL_VEHICLES = 'travel_time_all_vehicles';
const PASSENGER_VEHICLES = 'travel_time_passenger_vehicles';
const FREIGHT_TRUCKS = 'travel_time_freight_trucks';

const MINUTES_PER_EPOCH = 5;
const HOURS_IN_DAY = 24;
const EPOCHS_IN_HOUR = 12;
const EPOCHS_IN_MEASURE_HOUR = 4;
const NUM_EPOCHS_PER_DAY = HOURS_IN_DAY * EPOCHS_IN_HOUR;
const NUM_EPOCHS_FOR_METRIC = HOURS_IN_DAY * EPOCHS_IN_MEASURE_HOUR;
const FIFTEENTH_PCTL = 0.15;
const TWENTIETH_PCTL = 0.2;
const FIFTIETH_PCTL = 0.5;
const EIGHTIETH_PCTL = 0.8;
const NINETYFIFTH_PCTL = 0.95;
const NUM_MONTHS_IN_YEAR = 12;
const NUM_DAYS_IN_WEEK = 7;
const SEC_PER_MINUTE = 60;

const PERCENTILES_FOR_MEASURES = {
  lottr: { upperPercentile: EIGHTIETH_PCTL,   lowerPercentile: FIFTIETH_PCTL },
  tttr:  { upperPercentile: NINETYFIFTH_PCTL, lowerPercentile: FIFTIETH_PCTL },

  // R1 — a truck reliability ratio read at the 80th percentile instead of the 95th.
  //
  // TTTR is federally required and stays exactly as it is. This runs alongside it on the SAME
  // truck data, and exists because the 95th percentile — not the truck stream — is what makes
  // TTTR unusable on most of the network:
  //
  //   * TTTR needs ~6,297 overnight bins for ±5% precision on 90% of segments, which only
  //     7.6% of TMCs reach; the ±0.05 absolute criterion needs ~57,800 bins where a year
  //     contains 14,600, so it is unreachable by ANY segment, ever.
  //   * p80/p50 on the identical data needs 195 bins — 297× cheaper — and 68.8% of TMCs
  //     clear it.
  //   * The 2×2 factorial (quantile pair × stream) attributes the cost: reading p95 costs
  //     2.4× on the dense stream and 4.9× on truck, while the truck stream itself costs only
  //     1.45–1.53×. At matched sample size truck-overnight is the EASIER of the two streams.
  //
  // See npmrds_analysis/h01b-downsampling-curves.html and recommendations.html §R1.
  // pm3 is forked from map21 precisely so it may carry measures the submittal does not.
  tttr_p80: { upperPercentile: EIGHTIETH_PCTL, lowerPercentile: FIFTIETH_PCTL },
};

const BIN_NAMES = {
  ALL: 'ALL',
  AMP: 'AMP',
  PMP: 'PMP',
  ALT_PMP: 'ALT_PMP',
  WE: 'WE',
  MIDD: 'MIDD',
  OVN: 'OVN',
  FREEFLOW: 'FREEFLOW',
};

const REPORTING_BINS = [
  { name: BIN_NAMES.ALL,      hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23], dow: [0,1,2,3,4,5,6] },
  { name: BIN_NAMES.AMP,      hours: [6,7,8,9],                              dow: [1,2,3,4,5] },
  { name: BIN_NAMES.PMP,      hours: [16,17,18,19],                          dow: [1,2,3,4,5] },
  { name: BIN_NAMES.ALT_PMP,  hours: [15,16,17,18],                          dow: [1,2,3,4,5] },
  { name: BIN_NAMES.WE,       hours: [6,7,8,9,10,11,12,13,14,15,16,17,18,19], dow: [0,6] },
  { name: BIN_NAMES.MIDD,     hours: [10,11,12,13,14,15],                    dow: [1,2,3,4,5] },
  { name: BIN_NAMES.OVN,      hours: [20,21,22,23,0,1,2,3,4,5],              dow: [0,1,2,3,4,5,6] },
  { name: BIN_NAMES.FREEFLOW, hours: [22,23,0,1,2,3,4],                      dow: [0,1,2,3,4,5,6] },
];

const FREEWAY = 'FREEWAY';
const NONFREEWAY = 'NONFREEWAY';

// 2018 FHWA column order (used by the legacy data-table writer in helpers.js).
// Kept verbatim because internal table column naming is unchanged — the 2023
// HPMS submittal CSV is generated by createHpmsCsv.js which has its own column
// ordering (OVN before WE for trucks, no `comments`, all-lowercase) sourced
// from hpms-spec-2023.js.
const MAP_21_FHWA_COL_ORDER = [
  'BeginDate',
  'StateCode',
  'TravelTimeCode',
  'FSystem',
  'UrbanCode',
  'FacilityType',
  'NHS',
  'SegmentLength',
  'Directionality',
  'DIRAADT',
  'OCCFAC',
  'LOTTRAMP', 'TTAMP50PCT', 'TTAMP80PCT',
  'LOTTRMIDD', 'TTMIDD50PCT', 'TTMIDD80PCT',
  'LOTTRPMP', 'TTPMP50PCT', 'TTPMP80PCT',
  'LOTTRWE', 'TTWE50PCT', 'TTWE80PCT',
  'TTTRAMP', 'TTTAMP50PCT', 'TTTAMP95PCT',
  'TTTRMIDD', 'TTTMIDD50PCT', 'TTTMIDD95PCT',
  'TTTRPMP', 'TTTPMP50PCT', 'TTTPMP95PCT',
  'TTTRWE', 'TTTWE50PCT', 'TTTWE95PCT',
  'TTTROVN', 'TTTOVN50PCT', 'TTTOVN95PCT',
  'PHED',
  'MetricSource',
  'COMMENTS',
].map((col) => col.toLowerCase());

module.exports = {
  FREEWAY,
  NONFREEWAY,
  REPORTING_BINS,
  BIN_NAMES,
  NPMRDS_CH_SCHEMA_NAME,
  ALL_VEHICLES,
  PASSENGER_VEHICLES,
  FREIGHT_TRUCKS,
  MINUTES_PER_EPOCH,
  HOURS_IN_DAY,
  EPOCHS_IN_HOUR,
  EPOCHS_IN_MEASURE_HOUR,
  NUM_EPOCHS_PER_DAY,
  NUM_EPOCHS_FOR_METRIC,
  FIFTEENTH_PCTL,
  TWENTIETH_PCTL,
  FIFTIETH_PCTL,
  EIGHTIETH_PCTL,
  NINETYFIFTH_PCTL,
  PERCENTILES_FOR_MEASURES,
  NUM_MONTHS_IN_YEAR,
  NUM_DAYS_IN_WEEK,
  SEC_PER_MINUTE,
  MAP_21_FHWA_COL_ORDER,
};
