export const routeTagBrowserModalTheme = {
  wrapper: 'flex flex-col h-[70vh] max-h-[640px]',
  header: 'text-base font-bold text-slate-800 mb-1',
  breadcrumb: 'flex items-center flex-wrap gap-1 text-xs text-slate-500 mb-2',
  breadcrumbStep: 'hover:text-blue-600 hover:underline cursor-pointer',
  breadcrumbStepCurrent: 'text-slate-700 font-semibold',
  breadcrumbSep: 'text-slate-300',
  searchWrapper: 'flex items-center gap-1.5 mb-2',
  searchIcon: 'w-3.5 h-3.5 text-slate-400 shrink-0',
  body: 'flex-1 min-h-0 overflow-y-auto',
  categoryGrid: 'grid grid-cols-2 sm:grid-cols-3 gap-2 mt-1',
  categoryTile: 'flex flex-col items-start gap-0.5 p-3 bg-slate-50 border border-slate-200 rounded-lg hover:bg-slate-100 text-left',
  categoryTileLabel: 'text-sm font-semibold text-slate-700',
  categoryTileHint: 'text-[11px] text-slate-400',
  sectionLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mt-3 mb-1',
  valueList: 'grid grid-cols-2 sm:grid-cols-3 gap-1.5',
  valueItem: 'w-full text-left px-2 py-1.5 bg-slate-50 border border-slate-200 rounded hover:bg-slate-100 text-sm text-slate-700 truncate',
  routeList: 'space-y-1',
  routeItem: 'w-full flex items-center gap-2 p-1.5 bg-slate-50 border border-slate-200 rounded hover:bg-slate-100 text-left',
  routeItemSelected: 'w-full flex items-center gap-2 p-1.5 bg-blue-50 border border-blue-300 rounded hover:bg-blue-100 text-left',
  routeCheckbox: 'shrink-0',
  routeName: 'text-sm text-slate-700 truncate flex-1 min-w-0',
  alreadyAddedBadge: 'px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide bg-amber-100 text-amber-700 border border-amber-200 shrink-0',
  routeMeta: 'text-[11px] text-slate-400 shrink-0',
  loading: 'text-gray-500 text-sm p-2',
  empty: 'text-gray-400 italic text-sm p-2',
  error: 'text-red-500 mt-1 text-xs',
  footer: 'flex items-center justify-between gap-2 pt-3 mt-2 border-t border-slate-200',
  footerCount: 'text-xs text-slate-500',
  footerButtons: 'flex items-center gap-2',
};
