export const reportRouteListTheme = {
  wrapper: 'p-3 bg-white border border-slate-200 rounded-lg shadow-sm',
  title: 'text-sm font-bold text-slate-800 mb-2',
  titleWrapper: 'flex justify-between items-center text-sm font-bold text-slate-800 mb-2',
  routeCount: 'ml-1.5 font-normal text-slate-400',
  searchWrapper: 'flex items-center gap-1 mt-1 mb-2',
  list: 'mt-2 space-y-2',
  row: 'bg-slate-50 border border-slate-200 rounded-lg p-2 flex flex-col',
  rowContainer: 'flex flex-col w-full',
  rowHeader: 'flex items-center justify-between w-full p-1',
  routeTitle: 'font-semibold text-slate-700 text-sm truncate flex-1 min-w-0',
  unassignedBadge: 'px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide bg-amber-100 text-amber-700 border border-amber-200 shrink-0',
  editContainer: 'flex items-center gap-1 h-8 min-w-0',
  editInputWrapper: 'h-7 flex items-center',
  expandedContainer: 'mt-2 p-2 bg-white border-t border-slate-100 rounded-b-lg space-y-2',
  tmcWrapper: 'space-y-1',
  tmcLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider',
  tmcList: 'text-[11px] text-slate-600 bg-slate-50 p-1.5 rounded border border-slate-100',
  tmcMoreToggle: 'text-[11px] font-semibold text-blue-600 hover:text-blue-800 cursor-pointer ml-1',
  dateInputsContainer: 'flex flex-col gap-2',
  dateInputFlex: 'flex gap-1',
  dateInputWrapper: 'flex-1',
  dateLabel: 'block text-[11px] font-semibold text-slate-600 mb-0.5',
  dateRangeLabel: 'block text-[11px] font-semibold text-slate-700',
  peakPresetsWrapper: 'flex flex-wrap items-center gap-1',
  peakPresetLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mr-0.5',
  peakPresetPill: 'px-1.5 py-0.5 rounded text-[11px] border bg-slate-100 text-slate-600 border-slate-200 hover:bg-slate-200 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-slate-100',
  dowWrapper: 'flex flex-wrap items-center gap-1',
  dowSummary: 'text-[11px] text-slate-500 italic',
  dowDayPill: 'w-6 text-center px-1 py-0.5 rounded text-[11px] border',
  dowDayPillActive: 'bg-blue-100 text-blue-700 border-blue-300 hover:bg-blue-200',
  dowDayPillIdle: 'bg-slate-100 text-slate-400 border-slate-200 hover:bg-slate-200',
  dateModeWrapper: 'flex items-center gap-1.5',
  dateModeLabel: 'text-[11px] font-semibold text-slate-600',
  deriveControlsWrapper: 'space-y-1.5 p-1.5 bg-blue-50 border border-blue-100 rounded',
  deriveFormulaError: 'text-[11px] text-red-600',
  rowHeaderWrapper: 'flex justify-between items-center w-full',
  iconContainer: 'flex items-center gap-0.5 min-w-0 flex-1',
  reorderButtons: 'flex gap-0.5 items-center',
  loading: 'text-gray-500 text-sm',
  // Collapsed-by-default one-line summary that replaces the old always-on
  // "Fixed dates — base for ..." paragraph. Click to reveal the full read-only
  // range/weekday detail; irrelevant while actively editing (full controls show
  // unconditionally then).
  dateSummaryRow: 'w-full flex items-center justify-between gap-2 text-left bg-transparent border-none p-0 cursor-pointer',
  dateSummaryText: 'text-[11px] text-slate-600 truncate',
  sectionToggleChevron: 'w-3 h-3 text-slate-400 shrink-0',
  // "Base for N routes" — a standing fact about a base row, independent of
  // whether its own date detail is expanded.
  dependentsRow: 'pt-1',
  dependentsToggle: 'flex items-center gap-1 text-[11px] text-slate-600 bg-transparent border-none p-0 cursor-pointer',
  dependentsPillList: 'flex flex-wrap gap-1 mt-1.5',
  miniPill: 'px-1.5 py-0.5 rounded-full text-[10.5px] border bg-slate-50 text-slate-600 border-slate-200',
  skeletonWrapper: 'mt-2 space-y-2',
  skeletonRow: 'h-11 rounded-lg bg-slate-100 border border-slate-200 animate-pulse',
  empty: 'text-gray-400 italic text-sm',
  addForm: 'mt-2 p-1.5 bg-gray-50 rounded text-sm',
  addRouteWrapper: 'mb-3 pb-3 border-b border-slate-200',
  addRouteInputWrapper: 'flex items-center gap-1.5',
  addRouteSearchIcon: 'w-3.5 h-3.5 text-slate-400 shrink-0',
  addRouteJustAdded: 'text-[11px] text-emerald-700 mt-1',
  addRouteResultsLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mt-2 mb-1',
  addRouteResults: 'space-y-1 max-h-56 overflow-y-auto',
  addRouteResultItem: 'w-full flex items-center gap-1.5 p-1.5 bg-slate-50 border border-slate-200 rounded hover:bg-slate-100 text-left',
  addRouteResultName: 'text-sm text-slate-700 truncate flex-1 min-w-0',
  addRouteResultMeta: 'text-[11px] text-slate-400 shrink-0',
  addRouteResultIcon: 'w-3 h-3 text-slate-400 shrink-0',
  error: 'text-red-500 mt-1 text-xs',
  // Graphs: assigned/unassigned rendered as two labeled groups instead of one flat
  // alphabetical wrap, plus a summary line so "6 of 9" reads at a glance.
  graphChipsWrapper: 'flex flex-col gap-1.5 pt-2 mt-2 border-t border-slate-100',
  graphsSummaryLine: 'text-[11px] text-slate-500',
  graphGroup: 'flex flex-wrap items-center gap-1',
  graphGroupLabel: 'text-[10px] font-bold text-slate-400 uppercase tracking-wider mr-0.5',
  graphChip: 'px-1.5 py-0.5 rounded text-[11px] border bg-slate-100 text-slate-500 border-slate-200 hover:bg-slate-200',
  graphChipActive: 'px-1.5 py-0.5 rounded text-[11px] border bg-blue-100 text-blue-700 border-blue-300 hover:bg-blue-200',
  colorDot: 'w-2.5 h-2.5 rounded-full flex-shrink-0 border border-slate-300',
  // Appearance: collapsed to a swatch + label by default — the full ColorPicker
  // (swatch grid + gradient + hue bar) only mounts once an author asks for it.
  colorSection: 'pt-2 mt-2 border-t border-slate-100',
  colorSwatchToggle: 'w-full flex items-center gap-1.5 text-left bg-transparent border-none p-0 cursor-pointer',
  colorSwatchDot: 'w-4 h-4 rounded-full flex-shrink-0 border border-slate-300',
  colorSwatchLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider flex-1',
  colorPickerBody: 'mt-1.5',
  dynamicToggleWrapper: 'flex items-center gap-2 mb-3 pb-3 border-b border-slate-200',
  dynamicToggleLabel: 'text-[11px] text-slate-500',
  // Row-header overflow menu — Remove now lives here instead of a full-width
  // danger button competing with routine controls on every expanded row.
  // flex items-center (not just `relative`) — without it this wrapper is a plain
  // block box around an inline-block Button, and the button sits at the wrapper's
  // line-box position rather than centered in it, landing a few px off from the
  // reorder buttons beside it (real bug, caught live 2026-08-05).
  kebabWrapper: 'relative flex items-center',
  kebabMenu: 'absolute right-0 top-full mt-1 z-10 min-w-[160px] bg-white border border-slate-200 rounded-lg shadow-lg p-1',
  kebabMenuItem: 'w-full flex items-center gap-1.5 text-left px-2 py-1.5 rounded text-[12px] text-slate-700 hover:bg-slate-100',
  kebabMenuItemDanger: 'w-full flex items-center gap-1.5 text-left px-2 py-1.5 rounded text-[12px] text-red-600 hover:bg-red-50 disabled:opacity-40 disabled:cursor-not-allowed',
};
