export const reportRouteListTheme = {
  wrapper: 'p-3 bg-white border border-slate-200 rounded-lg shadow-sm',
  title: 'text-sm font-bold text-slate-800 mb-2',
  titleWrapper: 'flex justify-between items-center text-sm font-bold text-slate-800 mb-2',
  routeCount: 'ml-1.5 font-normal text-slate-400',
  searchWrapper: 'flex items-center gap-1 mt-1 mb-2',
  list: 'mt-2 space-y-2',
  row: 'bg-slate-50 border border-slate-200 rounded-lg p-2 flex flex-col',
  rowContainer: 'flex flex-col w-full',
  rowHeader: 'flex items-center justify-between w-full p-1',
  routeTitle: 'font-semibold text-slate-700 text-sm truncate flex-1 min-w-0',
  unassignedBadge: 'px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide bg-amber-100 text-amber-700 border border-amber-200 shrink-0',
  editContainer: 'flex items-center gap-1 h-8 min-w-0',
  editInputWrapper: 'h-7 flex items-center',
  expandedContainer: 'mt-2 p-2 bg-white border-t border-slate-100 rounded-b-lg space-y-2',
  tmcWrapper: 'space-y-1',
  tmcLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider',
  tmcList: 'text-[11px] text-slate-600 bg-slate-50 p-1.5 rounded border border-slate-100',
  tmcMoreToggle: 'text-[11px] font-semibold text-blue-600 hover:text-blue-800 cursor-pointer ml-1',
  dateInputsContainer: 'flex flex-col gap-2',
  dateInputFlex: 'flex gap-1',
  dateInputWrapper: 'flex-1',
  dateLabel: 'block text-[11px] font-semibold text-slate-600 mb-0.5',
  dateRangeLabel: 'block text-[11px] font-semibold text-slate-700',
  peakPresetsWrapper: 'flex flex-wrap items-center gap-1',
  peakPresetLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mr-0.5',
  peakPresetPill: 'px-1.5 py-0.5 rounded text-[11px] border bg-slate-100 text-slate-600 border-slate-200 hover:bg-slate-200 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-slate-100',
  dowWrapper: 'flex flex-wrap items-center gap-1',
  dowSummary: 'text-[11px] text-slate-500 italic',
  dowDayPill: 'w-6 text-center px-1 py-0.5 rounded text-[11px] border',
  dowDayPillActive: 'bg-blue-100 text-blue-700 border-blue-300 hover:bg-blue-200',
  dowDayPillIdle: 'bg-slate-100 text-slate-400 border-slate-200 hover:bg-slate-200',
  rowHeaderWrapper: 'flex justify-between items-center w-full',
  iconContainer: 'flex items-center gap-0.5 min-w-0 flex-1',
  reorderButtons: 'flex gap-0.5 items-center',
  removeButtonWrapper: 'flex justify-end mt-1',
  loading: 'text-gray-500 text-sm',
  skeletonWrapper: 'mt-2 space-y-2',
  skeletonRow: 'h-11 rounded-lg bg-slate-100 border border-slate-200 animate-pulse',
  empty: 'text-gray-400 italic text-sm',
  addForm: 'mt-2 p-1.5 bg-gray-50 rounded text-sm',
  addRouteWrapper: 'mb-3 pb-3 border-b border-slate-200',
  addRouteInputWrapper: 'flex items-center gap-1.5',
  addRouteSearchIcon: 'w-3.5 h-3.5 text-slate-400 shrink-0',
  addRouteJustAdded: 'text-[11px] text-emerald-700 mt-1',
  addRouteResultsLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mt-2 mb-1',
  addRouteResults: 'space-y-1 max-h-56 overflow-y-auto',
  addRouteResultItem: 'w-full flex items-center gap-1.5 p-1.5 bg-slate-50 border border-slate-200 rounded hover:bg-slate-100 text-left',
  addRouteResultName: 'text-sm text-slate-700 truncate flex-1 min-w-0',
  addRouteResultMeta: 'text-[11px] text-slate-400 shrink-0',
  addRouteResultIcon: 'w-3 h-3 text-slate-400 shrink-0',
  error: 'text-red-500 mt-1 text-xs',
  graphChipsWrapper: 'flex flex-wrap items-center gap-1 pt-2 mt-2 border-t border-slate-100',
  graphChipsLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider mr-1',
  graphChip: 'px-1.5 py-0.5 rounded text-[11px] border bg-slate-100 text-slate-500 border-slate-200 hover:bg-slate-200',
  graphChipActive: 'px-1.5 py-0.5 rounded text-[11px] border bg-blue-100 text-blue-700 border-blue-300 hover:bg-blue-200',
  colorDot: 'w-2.5 h-2.5 rounded-full flex-shrink-0 border border-slate-300',
  colorSection: 'space-y-1 pt-2 mt-2 border-t border-slate-100',
  colorSectionLabel: 'text-[11px] font-bold text-slate-500 uppercase tracking-wider'
};
