export const reportRouteListTheme = {
  wrapper: 'p-4 border rounded shadow-sm',
  title: 'text-lg font-bold mb-2',
  list: 'mt-2 space-y-2',
  row: 'border-b flex justify-between items-center m-0',
  rowContainer: 'flex flex-col w-full',
  rowHeader: 'flex items-center justify-between w-full p-2',
  routeTitle: 'font-semibold',
  editContainer: 'flex items-center gap-2 h-10',
  editInputWrapper: 'h-8 flex items-center',
  expandedContainer: 'p-4 bg-gray-50 space-y-4',
  tmcWrapper: 'space-y-1',
  tmcLabel: 'text-xs font-bold text-gray-700 uppercase tracking-wider',
  tmcList: 'text-xs text-gray-600  rounded',
  dateInputsContainer: 'flex gap-4',
  dateInputWrapper: 'flex-1',
  dateLabel: 'block text-xs font-semibold text-gray-700 mb-1',
  removeButtonWrapper: 'flex justify-end mt-2',
  loading: 'text-gray-500',
  empty: 'text-gray-400 italic',
  addForm: 'mt-4 p-2 bg-gray-50 rounded',
  error: 'text-red-500 mt-2'
};
