const { WEEKDAY, WEEKEND } = require('./dayTypes.js');
const {
  NO2LOW_CONGESTION,
  MODERATE_CONGESTION,
  SEVERE_CONGESTION
} = require('./congestionLevels.js');
const { AM_PEAK, EVEN_DIST, PM_PEAK } = require('./directionalities.js');
const { FREEWAY, NONFREEWAY } = require('./functionalClasses.js');

const trafficDistributionProfiles = [
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${AM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${AM_PEAK}_${NONFREEWAY}`,
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${EVEN_DIST}_${FREEWAY}`,
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${EVEN_DIST}_${NONFREEWAY}`,
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${PM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${NO2LOW_CONGESTION}_${PM_PEAK}_${NONFREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${AM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${AM_PEAK}_${NONFREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${EVEN_DIST}_${FREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${EVEN_DIST}_${NONFREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${PM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${MODERATE_CONGESTION}_${PM_PEAK}_${NONFREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${AM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${AM_PEAK}_${NONFREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${EVEN_DIST}_${FREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${EVEN_DIST}_${NONFREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${PM_PEAK}_${FREEWAY}`,
  `${WEEKDAY}_${SEVERE_CONGESTION}_${PM_PEAK}_${NONFREEWAY}`,
  `${WEEKEND}_${FREEWAY}`,
  `${WEEKEND}_${NONFREEWAY}`
].reduce((acc, tdp) => {
  acc[tdp] = tdp;
  return acc;
}, {});

module.exports = trafficDistributionProfiles;
