// Brand-neutral local fallback for the EditorMockup section component. The live
// skin comes from theme.pages.editorMockup — see tessera-theme-v6.js's
// `pagesTheme.editorMockup`; this only covers keys the theme doesn't define.
export const editorMockupTheme = {
  wrapper: 'relative',
  frame: 'bg-white border border-gray-200 rounded-lg shadow-md overflow-hidden',
  titlebar: 'h-11 border-b border-gray-200 flex items-center gap-2 px-4',
  trafficLights: 'flex gap-1.5',
  trafficDot: 'w-2.5 h-2.5 rounded-full border border-gray-300',
  path: 'text-xs text-gray-500 ml-3 truncate font-mono',
  badge: 'inline-flex items-center gap-1.5 text-xs text-amber-600 bg-amber-50 rounded-full px-2 py-0.5',
  cta: 'inline-flex items-center gap-1.5 text-xs text-white bg-blue-600 rounded-md px-2.5 py-1',
  ctaIcon: 'w-3.5 h-3.5',
  body: 'flex',
  sidebar: 'hidden md:flex flex-col w-48 flex-none border-r border-gray-200 py-3 px-2.5 gap-0.5',
  sidebarItem: 'flex items-center gap-2 px-2 py-1.5 rounded-md text-sm text-gray-600',
  sidebarItemActive: 'flex items-center gap-2 px-2 py-1.5 rounded-md bg-blue-50 text-blue-600 text-sm font-medium',
  sidebarIcon: 'w-3.5 h-3.5',
  canvas: 'flex-1 min-w-0 relative bg-gray-50 p-4 sm:p-6',
  canvasGrid: 'relative grid grid-cols-12 gap-1.5',
  blockPanel: 'bg-white border border-gray-200 rounded-md px-4 py-3',
  blockTitle: 'text-base font-semibold text-gray-900',
  blockSubtitle: 'text-xs text-gray-500 mt-0.5',
  statLabel: 'text-xs text-gray-500',
  statValue: 'text-lg font-semibold text-gray-900 tabular-nums',
  tablePanel: 'bg-white border border-gray-200 rounded-md overflow-hidden',
  tableHeader: 'px-3 py-2 border-b border-gray-200',
  tableHeaderLabel: 'text-xs text-gray-500',
  tableRow: 'px-3 py-1.5 flex justify-between text-xs',
  tableRowMeta: 'text-gray-500 tabular-nums',
  dropzone: 'h-full min-h-[104px] border-2 border-dashed border-blue-300 bg-blue-50 rounded-md flex items-center justify-center',
  dropzoneLabel: 'text-xs text-blue-600',
  selectedPanel: 'relative border-2 border-blue-500 rounded-md bg-white px-4 py-4',
  selectedToolbar: 'absolute -top-4 right-2 flex items-center gap-2 bg-white border border-gray-200 rounded-md px-2 py-1 shadow',
  selectedToolbarIcon: 'w-3.5 h-3.5 text-gray-500',
  selectedText: 'text-sm text-gray-900',
  labeledPanel: 'bg-white border border-gray-200 rounded-md px-3 py-6 flex items-center justify-between',
  labeledText: 'text-sm text-gray-600',
  labeledMeta: 'text-xs text-blue-600',
  dragCard: 'absolute bottom-6 right-4 sm:right-10 w-48 sm:w-56 bg-white border border-blue-500 rounded-lg p-3 shadow-lg z-10',
  dragCardHeader: 'flex items-center gap-1.5 pb-2',
  dragCardGrip: 'w-3.5 h-3.5 text-gray-400',
  dragCardLabel: 'text-xs text-gray-600',
  dragCardBars: 'flex items-end gap-1 h-14',
  dragCardBar: 'flex-1 rounded-t-sm bg-blue-500',
  annotationTopRight: 'hidden lg:block absolute -top-4 right-10 rotate-2 text-sm text-blue-600 font-cursive',
  annotationBottomLeft: 'hidden lg:block absolute -bottom-7 left-10 -rotate-2 text-sm text-gray-500 font-cursive',
};
