const countyFipsToRegion = {
  "09000": {
    region: null,
    region_code: null,
    county_name: "CONNECTICUT",
  },
  "09001": {
    region: null,
    region_code: null,
    county_name: "FAIRFIELD",
  },
  "09003": {
    region: null,
    region_code: null,
    county_name: "HARTFORD",
  },
  "09005": {
    region: null,
    region_code: null,
    county_name: "LITCHFIELD",
  },
  "09007": {
    region: null,
    region_code: null,
    county_name: "MIDDLESEX",
  },
  "09009": {
    region: null,
    region_code: null,
    county_name: "NEW HAVEN",
  },
  "09011": {
    region: null,
    region_code: null,
    county_name: "NEW LONDON",
  },
  "09013": {
    region: null,
    region_code: null,
    county_name: "TOLLAND",
  },
  "09015": {
    region: null,
    region_code: null,
    county_name: "WINDHAM",
  },
  "34000": {
    region: null,
    region_co: null,
    county_name: "NEW JERSEY",
  },
  "34001": {
    region: null,
    region_co: null,
    county_name: "ATLANTIC",
  },
  "34003": {
    region: null,
    region_co: null,
    county_name: "BERGEN",
  },
  "34005": {
    region: null,
    region_co: null,
    county_name: "BURLINGTON",
  },
  "34007": {
    region: null,
    region_co: null,
    county_name: "CAMDEN",
  },
  "34009": {
    region: null,
    region_co: null,
    county_name: "CAPE MAY",
  },
  "34011": {
    region: null,
    region_co: null,
    county_name: "CUMBERLAND",
  },
  "34013": {
    region: null,
    region_co: null,
    county_name: "ESSEX",
  },
  "34015": {
    region: null,
    region_co: null,
    county_name: "GLOUCESTER",
  },
  "34017": {
    region: null,
    region_co: null,
    county_name: "HUDSON",
  },
  "34019": {
    region: null,
    region_co: null,
    county_name: "HUNTERDON",
  },
  "34021": {
    region: null,
    region_co: null,
    county_name: "MERCER",
  },
  "34023": {
    region: null,
    region_co: null,
    county_name: "MIDDLESEX",
  },
  "34025": {
    region: null,
    region_co: null,
    county_name: "MONMOUTH",
  },
  "34027": {
    region: null,
    region_co: null,
    county_name: "MORRIS",
  },
  "34029": {
    region: null,
    region_co: null,
    county_name: "OCEAN",
  },
  "34031": {
    region: null,
    region_co: null,
    county_name: "PASSAIC",
  },
  "34033": {
    region: null,
    region_co: null,
    county_name: "SALEM",
  },
  "34035": {
    region: null,
    region_co: null,
    county_name: "SOMERSET",
  },
  "34037": {
    region: null,
    region_co: null,
    county_name: "SUSSEX",
  },
  "34039": {
    region: null,
    region_co: null,
    county_name: "UNION",
  },
  "34041": {
    region: null,
    region_co: null,
    county_name: "WARREN",
  },
  "36001": {
    region: 1,
    region_name: "Capital District",
    region_co: 11,
    county_name: "ALBANY",
  },
  "36031": {
    region: 1,
    region_name: "Capital District",
    region_co: 12,
    county_name: "ESSEX",
  },
  "36039": {
    region: 1,
    region_name: "Capital District",
    region_co: 13,
    county_name: "GREENE",
  },
  "36083": {
    region: 1,
    region_name: "Capital District",
    region_co: 14,
    county_name: "RENSSELAER",
  },
  "36091": {
    region: 1,
    region_name: "Capital District",
    region_co: 15,
    county_name: "SARATOGA",
  },
  "36093": {
    region: 1,
    region_name: "Capital District",
    region_co: 16,
    county_name: "SCHENECTADY",
  },
  "36113": {
    region: 1,
    region_name: "Capital District",
    region_co: 17,
    county_name: "WARREN",
  },
  "36115": {
    region: 1,
    region_name: "Capital District",
    region_co: 18,
    county_name: "WASHINGTON",
  },
  "36035": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 21,
    county_name: "FULTON",
  },
  "36041": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 22,
    county_name: "HAMILTON",
  },
  "36043": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 23,
    county_name: "HERKIMER",
  },
  "36053": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 24,
    county_name: "MADISON",
  },
  "36057": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 25,
    county_name: "MONTGOMERY",
  },
  "36065": {
    region: 2,
    region_name: "Mohawk Valley",
    region_co: 26,
    county_name: "ONEIDA",
  },
  "36011": {
    region: 3,
    region_name: "Central New York",
    region_co: 31,
    county_name: "CAYUGA",
  },
  "36023": {
    region: 3,
    region_name: "Central New York",
    region_co: 32,
    county_name: "CORTLAND",
  },
  "36067": {
    region: 3,
    region_name: "Central New York",
    region_co: 33,
    county_name: "ONONDAGA",
  },
  "36075": {
    region: 3,
    region_name: "Central New York",
    region_co: 34,
    county_name: "OSWEGO",
  },
  "36099": {
    region: 3,
    region_name: "Central New York",
    region_co: 35,
    county_name: "SENECA",
  },
  "36109": {
    region: 3,
    region_name: "Central New York",
    region_co: 36,
    county_name: "TOMPKINS",
  },
  "36037": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 41,
    county_name: "GENESEE",
  },
  "36051": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 42,
    county_name: "LIVINGSTON",
  },
  "36055": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 43,
    county_name: "MONROE",
  },
  "36069": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 44,
    county_name: "ONTARIO",
  },
  "36073": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 45,
    county_name: "ORLEANS",
  },
  "36121": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 46,
    county_name: "WYOMING",
  },
  "36117": {
    region: 4,
    region_name: "Genesee Valley",
    region_co: 47,
    county_name: "WAYNE",
  },
  "36009": {
    region: 5,
    region_name: "Western New York",
    region_co: 51,
    county_name: "CATTARAUGUS",
  },
  "36013": {
    region: 5,
    region_name: "Western New York",
    region_co: 52,
    county_name: "CHAUTAUQUA",
  },
  "36029": {
    region: 5,
    region_name: "Western New York",
    region_co: 53,
    county_name: "ERIE",
  },
  "36063": {
    region: 5,
    region_name: "Western New York",
    region_co: 54,
    county_name: "NIAGARA",
  },
  "36003": {
    region: 6,
    region_name: "Southern Tier/Central New York",
    region_co: 61,
    county_name: "ALLEGANY",
  },
  "36015": {
    region: 6,
    region_name: "Southern Tier/Central New York",
    region_co: 62,
    county_name: "CHEMUNG",
  },
  "36097": {
    region: 6,
    region_name: "Southern Tier/Central New York",
    region_co: 63,
    county_name: "SCHUYLER",
  },
  "36101": {
    region: 6,
    region_name: "Southern Tier/Central New York",
    region_co: 64,
    county_name: "STEUBEN",
  },
  "36123": {
    region: 6,
    region_name: "Southern Tier/Central New York",
    region_co: 66,
    county_name: "YATES",
  },
  "36019": {
    region: 7,
    region_name: "North Country",
    region_co: 71,
    county_name: "CLINTON",
  },
  "36033": {
    region: 7,
    region_name: "North Country",
    region_co: 72,
    county_name: "FRANKLIN",
  },
  "36045": {
    region: 7,
    region_name: "North Country",
    region_co: 73,
    county_name: "JEFFERSON",
  },
  "36049": {
    region: 7,
    region_name: "North Country",
    region_co: 74,
    county_name: "LEWIS",
  },
  "36089": {
    region: 7,
    region_name: "North Country",
    region_co: 75,
    county_name: "ST LAWRENCE",
  },
  "36021": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 81,
    county_name: "COLUMBIA",
  },
  "36027": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 82,
    county_name: "DUTCHESS",
  },
  "36071": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 83,
    county_name: "ORANGE",
  },
  "36079": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 84,
    county_name: "PUTNAM",
  },
  "36087": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 85,
    county_name: "ROCKLAND",
  },
  "36111": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 86,
    county_name: "ULSTER",
  },
  "36119": {
    region: 8,
    region_name: "Hudson Valley",
    region_co: 87,
    county_name: "WESTCHESTER",
  },
  "36007": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 91,
    county_name: "BROOME",
  },
  "36017": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 92,
    county_name: "CHENANGO",
  },
  "36025": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 93,
    county_name: "DELAWARE",
  },
  "36077": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 94,
    county_name: "OTSEGO",
  },
  "36095": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 95,
    county_name: "SCHOHARIE",
  },
  "36105": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 96,
    county_name: "SULLIVAN",
  },
  "36107": {
    region: 9,
    region_name: "Southern Tier",
    region_co: 97,
    county_name: "TIOGA",
  },
  "36059": {
    region: 10,
    region_name: "Long Island",
    region_co: 3,
    county_name: "NASSAU",
  },
  "36103": {
    region: 10,
    region_name: "Long Island",
    region_co: 7,
    county_name: "SUFFOLK",
  },
  "36005": {
    region: 11,
    region_name: "New York City",
    region_co: 1,
    county_name: "BRONX",
  },
  "36047": {
    region: 11,
    region_name: "New York City",
    region_co: 2,
    county_name: "KINGS",
  },
  "36061": {
    region: 11,
    region_name: "New York City",
    region_co: 4,
    county_name: "NEW YORK",
  },
  "36081": {
    region: 11,
    region_name: "New York City",
    region_co: 5,
    county_name: "QUEENS",
  },
  "36085": {
    region: 11,
    region_name: "New York City",
    region_co: 6,
    county_name: "RICHMOND",
  },
};

module.exports = { countyFipsToRegion };
