/* SPECIMEN SWITCHER — design-system REVIEW WIDGET for action-view.html and
 * action-edit.html. Ten real actions (specimen-data.js, generated by
 * references/actions/scripts/20_specimen_data.mjs) spanning very complete →
 * very empty, so a reviewer can see how the pages hold up across the real
 * data's range.
 *
 * This is reviewer scaffolding, a peer of ds-nav.js: deliberately styled
 * NOTHING like the mny design (dark panel, monospace, pinned to the viewport
 * corner) so it can't be mistaken for product chrome, and it NEVER ships on a
 * live DMS page.
 *
 * Mechanics: picking a specimen stores its id (sessionStorage) and reloads;
 * on load, a non-default specimen re-renders the page's baked markup through
 * the data-spec hooks (view) or field ids (edit). The default specimen is the
 * page's own hand-authored HTML, untouched.
 */
(function () {
  var SPECIMENS = window.MNY_SPECIMENS || [];
  var DEFAULT_ID = 1100379; // the baked page — Kohlertown Route 52
  var KEY = 'mnySpecimenId';
  var IS_EDIT = !!document.getElementById('f-action-name');

  var esc = function (s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };
  var MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  var fmtDate = function (iso) {
    if (!iso) return null;
    var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
    if (!m) return iso;
    return Number(m[3]) + ' ' + MONTHS[Number(m[2]) - 1] + ' ' + m[1];
  };
  var q = function (name) { return document.querySelector('[data-spec="' + name + '"]'); };

  // ── shared vocab ───────────────────────────────────────────────────────────
  var NR_TEXT = '<span class="font-proxima text-[13px] text-mny-400 italic">Not Reported</span>';
  var Q_CHIP = '<a href="action-edit.html#screening" class="inline-flex items-center shrink-0 px-2 py-0.5 rounded-full border border-dashed border-mny-y700 bg-mny-y50 font-proxima text-[11px] font-[700] text-mny-900 hover:bg-[#F9EFDD]" title="Not answered yet — answer it on the edit page">?</a>';
  var CHECK_SVG = '<svg xmlns="http://www.w3.org/2000/svg" class="size-4 text-mny-grn" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.7-9.3a1 1 0 00-1.4-1.4L9 10.6 7.7 9.3a1 1 0 00-1.4 1.4l2 2a1 1 0 001.4 0l4-4z" clip-rule="evenodd"/></svg>';
  var X_SVG = '<svg xmlns="http://www.w3.org/2000/svg" class="size-4 text-mny-red" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd"/></svg>';
  var SHMP_LABELS = {
    1: 'Protect &amp; improve the health and safety of all people &amp; communities',
    2: 'Federal, state &amp; local coordination',
    3: 'Protect existing property',
    4: 'Increase awareness',
    5: 'Preserve &amp; restore natural systems',
    6: 'Build stronger'
  };
  var STATUS_STYLE = {
    'In-Progress': { shell: 'bg-mny-400/15 border border-mny-400/50', dot: 'bg-mny-400', label: 'In-Progress' },
    'Completed': { shell: 'bg-mny-grn/15 border border-mny-grn/40', dot: 'bg-mny-grn', label: 'Completed' },
    'Proposed': { shell: 'bg-mny-50 border border-mny-200', dot: 'bg-mny-200', label: 'Proposed' },
    'Discontinued/Paused': { shell: 'bg-mny-y50 border border-mny-y700/60', dot: 'bg-mny-y700', label: 'Discontinued' }
  };
  var placeName = function (s) {
    return s.county === 'New York City' ? 'New York City' : s.county ? s.county + ' County' : 'New York State';
  };

  // ── VIEW page renderer ─────────────────────────────────────────────────────
  function renderView(s) {
    var jur = s.jurisdiction || placeName(s);
    var title = s.title ? esc(s.title) : '<span class="text-mny-400 italic normal-case">Untitled action</span>';

    q('crumb-county').textContent = (s.county ? (s.county === 'New York City' ? 'New York City' : s.county + ' County') : 'New York State') + ' Actions';
    q('crumb-jur').textContent = s.jurisdiction || (s.scope === 'State' ? 'Statewide' : placeName(s));
    q('h1').innerHTML = esc(jur) + ' <span class="text-mny-200 font-[400] px-1">|</span> ' + title;
    q('county-line').textContent = placeName(s);
    q('plan-chip').textContent = s.scope === 'State' ? 'State plan' : 'Local plan';

    var st = STATUS_STYLE[s.status];
    q('status-pill').outerHTML = st
      ? '<span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full ' + st.shell + ' font-proxima text-[12px] font-[600] text-mny-900" data-spec="status-pill"><span class="w-2 h-2 rounded-full ' + st.dot + '"></span>' + st.label + '</span>'
      : '<span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white border border-dashed border-mny-y700 font-proxima text-[12px] font-[600] text-mny-400 italic" data-spec="status-pill">Status Not Reported</span>';
    var jpPill = q('jp-pill');
    if (s.jp) {
      jpPill.style.display = '';
      jpPill.innerHTML = 'Jurisdictional priority <strong class="text-mny-900 font-[700]">' + esc(s.jp) + '</strong>';
    } else { jpPill.style.display = 'none'; }

    // the case
    var prob = q('problem');
    var h3 = prob.querySelector('h3').outerHTML;
    if (s.problem) {
      var m = /^(.+?[.!?])\s+([\s\S]+)$/.exec(s.problem);
      prob.innerHTML = h3 +
        '<p class="font-proxima text-[20px] text-mny-900 leading-[140%] mt-2.5">' + esc(m ? m[1] : s.problem) + '</p>' +
        (m ? '<p class="font-proxima text-[16px] text-mny-700 leading-[140%] mt-3">' + esc(m[2]) + '</p>' : '');
    } else {
      prob.innerHTML = h3 + '<p class="font-proxima text-[16px] text-mny-400 italic mt-2.5">Not Reported</p>';
    }
    q('solution').outerHTML = s.solution
      ? '<p class="font-proxima text-[16px] text-mny-700 leading-[145%] mt-2.5" data-spec="solution">' + esc(s.solution) + '</p>'
      : '<p class="font-proxima text-[16px] text-mny-400 italic mt-2.5" data-spec="solution">Not Reported</p>';
    var alt = q('alt-section');
    if (s.altAction) {
      alt.style.display = '';
      q('alt-name').textContent = s.altAction;
      q('alt-chip').style.display = s.altEval ? '' : 'none';
      if (s.altEval) q('alt-chip').innerHTML = 'Rejected — ' + esc(s.altEval.charAt(0).toLowerCase() + s.altEval.slice(1));
    } else { alt.style.display = 'none'; }

    // cost & benefit
    q('cost-range').innerHTML = s.costRange ? esc(s.costRange) : '<span class="text-[14px] font-[400] text-mny-400 italic">Not Reported</span>';
    q('cost-notes').innerHTML = s.costNotes ? esc(s.costNotes) : '<span class="text-mny-400 italic">Not Reported</span>';
    q('cost-reasonable').innerHTML = s.costReasonable === 'Yes'
      ? '<span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-mny-grn/15 border border-mny-grn/40 font-[600] text-mny-900">Yes</span>'
      : s.costReasonable === 'No'
        ? '<span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-mny-redk/10 border border-mny-redk/25 font-[600] text-mny-redk">No</span>'
        : '<span class="text-mny-400 italic">Not Reported</span>';
    q('why-pays').innerHTML = s.why_pays ? esc(s.why_pays) : '<span class="text-mny-400 italic">Not Reported</span>';

    // goals & community
    q('shmp').innerHTML = s.shmpGoals.length
      ? s.shmpGoals.map(function (g) {
          return '<span class="inline-flex items-start gap-2 font-proxima text-[13px] text-mny-900"><span class="size-5 shrink-0 rounded-full bg-mny-900 text-white font-display text-[11px] font-[600] flex items-center justify-center tabular-nums">' + g + '</span>' + SHMP_LABELS[g] + '</span>';
        }).join('')
      : NR_TEXT;
    q('lhmp-goals').innerHTML = s.lhmpGoals ? esc(s.lhmpGoals) : '<span class="text-mny-400 italic">Not Reported</span>';
    var comm = [
      ['Adapts to climate change', s.community.adapt],
      ['Mitigates climate change / reduces GHGs', s.community.ghg],
      ['Protects or assesses risk to vulnerable populations', s.community.vulnerable],
      ['Supports potential Community Rating System (CRS) points', s.community.crs],
      ['Aligns with a Climate Smart Communities action', s.community.csc],
      ['Environmental / historic preservation concerns', s.community.envHistoric]
    ];
    q('community').innerHTML = comm.map(function (row) {
      var chip = row[1] == null ? Q_CHIP
        : '<span class="inline-flex items-center shrink-0 px-2 py-0.5 rounded-full ' +
          (row[1] === 'Yes' ? 'bg-mny-900 text-white' : 'bg-mny-100 text-mny-700') +
          ' font-proxima text-[11px] font-[700]">' + esc(row[1]) + '</span>';
      return '<li class="flex items-center justify-between gap-3"><span class="font-proxima text-[13px] text-mny-700 leading-[1.35]">' + row[0] + '</span>' + chip + '</li>';
    }).join('');

    // key facts rail
    var right = function (v, bold) {
      return v ? '<span class="font-proxima text-[13px] text-mny-900 font-[600] text-right">' + esc(v) + '</span>'
               : '<span class="font-proxima text-[13px] text-mny-400 italic text-right">Not Reported</span>';
    };
    q('rail-lead').innerHTML = s.lead
      ? '<span class="block font-proxima text-[13px] text-mny-900 font-[600] leading-[1.3]">' + esc(s.lead) + '</span>' +
        (s.jurisdiction ? '<span class="block font-proxima text-[11px] text-mny-400">' + esc(s.jurisdiction) + '</span>' : '')
      : NR_TEXT;
    q('rail-cost').outerHTML = '<dd class="font-proxima text-[13px] ' + (s.costRange ? 'text-mny-900 font-[600]' : 'text-mny-400 italic') + ' text-right tabular-nums" data-spec="rail-cost">' + (s.costRange ? esc(s.costRange) : 'Not Reported') + '</dd>';
    q('rail-time').outerHTML = '<dd class="font-proxima text-[13px] ' + (s.time ? 'text-mny-900 font-[600]' : 'text-mny-400 italic') + ' text-right" data-spec="rail-time">' + (s.time ? esc(s.time) : 'Not Reported') + '</dd>';
    q('rail-funding').outerHTML = '<dd class="font-proxima text-[13px] ' + (s.funding ? 'text-mny-900 font-[600]' : 'text-mny-400 italic') + ' text-right leading-[1.4] max-w-[180px]" data-spec="rail-funding">' + (s.funding ? esc(s.funding) : 'Not Reported') + '</dd>';
    q('rail-mechanism').outerHTML = '<dd class="font-proxima text-[13px] ' + (s.mechanism ? 'text-mny-900 font-[600]' : 'text-mny-400 italic') + ' text-right" data-spec="rail-mechanism">' + (s.mechanism ? esc(s.mechanism) : 'Not Reported') + '</dd>';
    var hz = [];
    if (s.hazards[0]) hz.push('<span class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white border border-mny-200 font-proxima text-[13px] font-[600] text-mny-900">' + esc(s.hazards[0]) + '</span><span class="font-proxima text-[11px] text-mny-400">primary</span>');
    if (s.hazards[1]) hz.push('<span class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white border border-mny-100 font-proxima text-[12px] font-[600] text-mny-700">' + esc(s.hazards[1]) + '</span><span class="font-proxima text-[11px] text-mny-400">secondary</span>');
    q('rail-hazard').innerHTML = hz.length ? hz.join('') : NR_TEXT;
    var ty = s.types[0];
    if (ty) {
      var tm = /^(.*?)\s*\((.*)\)\s*$/.exec(ty);
      q('rail-type').innerHTML =
        '<span class="block font-proxima text-[13px] text-mny-900 font-[600] leading-[1.3]">' + esc(tm ? tm[1] : ty) + '</span>' +
        (tm ? '<span class="block font-proxima text-[11px] text-mny-700">' + esc(tm[2]) + '</span>' : '');
    } else { q('rail-type').innerHTML = NR_TEXT; }
    q('rail-assoc').outerHTML = s.assocRisk.length
      ? '<dd class="font-proxima text-[13px] text-mny-900 font-[600] text-right leading-[1.4] max-w-[180px]" data-spec="rail-assoc">' + s.assocRisk.map(esc).join(' · ') + '</dd>'
      : '<dd class="font-proxima text-[13px] text-mny-400 italic text-right" data-spec="rail-assoc">Not Reported</dd>';
    q('rail-jp').outerHTML = '<dd class="font-proxima text-[13px] ' + (s.jp ? 'text-mny-900 font-[600]' : 'text-mny-400 italic') + ' text-right" data-spec="rail-jp">' + (s.jp ? esc(s.jp) : 'Not Reported') + '</dd>';
    // readiness / maturity stay "Not Yet Assessed" — the fields don't exist in the data yet
    var checks = [
      ['Critical facility', s.flags.critical],
      ['Potential buyout', s.flags.buyout],
      ['Culvert', s.flags.culvert],
      ['Generator', s.flags.generator],
      ['RL/SRL', s.flags.rlsrl]
    ];
    q('rail-checks').innerHTML = checks.map(function (row) {
      var val = row[1] === 'Yes'
        ? '<span class="inline-flex items-center gap-1 font-proxima text-[12px] font-[700] text-mny-900">' + CHECK_SVG + 'Yes</span>'
        : row[1] === 'No'
          ? '<span class="inline-flex items-center gap-1 font-proxima text-[12px] font-[700] text-mny-700">' + X_SVG + 'No</span>'
          : Q_CHIP;
      return '<div class="flex items-center justify-between gap-2"><span class="font-proxima text-[13px] text-mny-700">' + row[0] + '</span>' + val + '</div>';
    }).join('');

    var loc;
    if (s.precision === 1 || s.precision === 2) {
      loc = 'Located at <strong class="text-mny-900 font-[600]">' + esc(s.address || s.geometry || 'a recorded site') + '</strong>' +
        (s.locationMethod && s.locationMethod.indexOf('recovered') === 0
          ? ' — recovered from the action’s own text' + (s.distKm != null ? ' (' + s.distKm.toFixed(2) + ' km off the centroid)' : '') + '.'
          : '.');
    } else if (s.precision === 3) {
      loc = 'No site coordinate recorded — mapped to the <strong class="text-mny-900 font-[600]">' + esc(s.jurisdiction || 'municipal') + ' centroid</strong>.';
    } else if (s.precision === 4) {
      loc = 'No site coordinate recorded — mapped to the <strong class="text-mny-900 font-[600]">' + (s.county === 'New York City' ? 'New York City citywide centroid' : esc(s.county || '') + ' County centroid') + '</strong>.';
    } else if (s.precision === 5) {
      loc = 'Statewide action — <strong class="text-mny-900 font-[600]">no point, by design</strong>.';
    } else {
      loc = 'No location signal of any kind — this action <strong class="text-mny-900 font-[600]">cannot be mapped</strong>.';
    }
    var addLink = (s.precision === 1 || s.precision === 2 || s.precision === 5) ? '' :
      '<dd class="mt-1.5"><a href="action-edit.html#location" class="inline-flex items-center gap-1 font-proxima text-[11px] font-[700] uppercase tracking-wider text-mny-y700 hover:text-mny-900">Add a coordinate <svg xmlns="http://www.w3.org/2000/svg" class="size-3" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.3 14.7a1 1 0 010-1.4L10.6 10 7.3 6.7a1 1 0 011.4-1.4l4 4a1 1 0 010 1.4l-4 4a1 1 0 01-1.4 0z" clip-rule="evenodd"/></svg></a></dd>';
    q('rail-location').innerHTML = '<dt class="font-proxima text-[13px] text-mny-700">Location</dt>' +
      '<dd class="font-proxima text-[13px] text-mny-700 leading-[1.45] mt-1">' + loc + '</dd>' + addLink;

    // action record
    q('rec-created').innerHTML = s.created ? esc(fmtDate(s.created)) : '<span class="text-mny-400 italic font-[400]">Not Reported</span>';
    q('rec-updated').innerHTML = s.statusDate ? esc(fmtDate(s.statusDate)) : '<span class="text-mny-400 italic font-[400]">Not Reported</span>';
    q('rec-source').textContent = s.scope === 'State' ? 'State (SHMP)' : 'Local (LHMP)';
    q('rec-lasthmp').innerHTML = s.lastHmp ? esc(s.lastHmp) : '<span class="text-mny-400 italic font-[400]">Not Reported</span>';

    // empty fields disclosure — recomputed for this specimen
    var pairs = [
      ['Site coordinates', s.geometry], ['Address', s.address],
      ['Estimated cost ($)', s.estCost],
      ['Alternative considered', s.altAction],
      ['Secondary hazard type', s.hazards[1]], ['Tertiary hazard type', s.hazards[2]],
      ['Secondary action type', s.types[1]], ['Tertiary action type', s.types[2]],
      ['Action status details', s.statusDetails],
      ['If completed: calculated cost', s.complCost],
      ['If completed: funding source(s)', s.complFunding],
      ['Lead NYS agency', s.leadNys], ['NYS agency abbreviation', s.nysAbbr],
      ['Partners', s.partners], ['Point of contact', s.poc],
      ['POC title', s.pocTitle], ['POC email', s.pocEmail]
    ];
    var empty = pairs.filter(function (p) { return !p[1]; });
    q('empty-count').textContent = 'Show ' + empty.length + ' empty field' + (empty.length === 1 ? '' : 's');
    q('empty-list').innerHTML = empty.map(function (p) {
      return '<span class="font-proxima text-[12px] text-mny-400">' + esc(p[0]) + '</span>';
    }).join('');
    q('empty-note').style.display = 'none'; // the footnote is Sullivan-specific

    q('page-id').textContent = 'Action id ' + s.id + ' · source 1029065 / view 1074456';
    document.title = 'MitigateNY — Action View (' + (s.title || 'Untitled action') + ')';
  }

  // ── EDIT page renderer ─────────────────────────────────────────────────────
  function renderEdit(s) {
    var setVal = function (id, v, emptyPlaceholder) {
      var el = document.getElementById(id);
      if (!el) return;
      el.value = v || '';
      el.classList.toggle('mny-field-empty', !v);
    };
    var setSel = function (id, v, emptyLabel) {
      var el = document.getElementById(id);
      if (!el) return;
      if (v) {
        var found = Array.prototype.some.call(el.options, function (o) { return o.value === v || o.text === v; });
        if (!found) {
          var o = document.createElement('option');
          o.text = v; el.add(o);
        }
        el.value = Array.prototype.find.call(el.options, function (o) { return o.value === v || o.text === v; }).value;
        el.classList.remove('mny-field-empty');
      } else {
        var blank = Array.prototype.find.call(el.options, function (o) { return o.value === ''; });
        if (!blank) {
          var b = document.createElement('option');
          b.value = ''; b.text = emptyLabel || '— Not answered —'; el.add(b, 0);
        }
        el.value = '';
        el.classList.add('mny-field-empty');
      }
    };

    setVal('f-action-name', s.title);
    setSel('f-jurisdiction', s.jurisdiction || (s.scope === 'State' ? 'Statewide' : s.county), '— No jurisdiction —');
    var statusMap = { 'Proposed': 'Proposed - Not Started', 'In-Progress': 'In-Progress', 'Completed': 'Completed', 'Discontinued/Paused': 'Discontinued' };
    setSel('f-status', s.status ? statusMap[s.status] || s.status : 'Progress Not Reported');
    setVal('f-status-date', s.statusDate);
    setVal('f-problem', s.problem);
    setVal('f-solution', s.solution);
    setVal('f-alt', s.altAction);
    setVal('f-alt-eval', s.altEval);
    setSel('f-cost-range', s.costRange, '— Not set —');
    setVal('f-est-cost', s.estCost);
    setSel('f-costs-reasonable', s.costReasonable);
    setVal('f-cost-notes', s.costNotes);
    setVal('f-cost-benefit', s.why_pays);
    // SHMP goal checkboxes ride in DOM order 1..6
    var goalBoxes = document.querySelectorAll('#screening fieldset input[type="checkbox"]');
    goalBoxes.forEach(function (box, i) { box.checked = s.shmpGoals.indexOf(i + 1) >= 0; });
    setVal('f-lhmp-goals', s.lhmpGoals);
    setSel('q5', s.community.adapt); setSel('q6', s.community.ghg);
    setSel('q9', s.community.vulnerable); setSel('q10', s.community.crs);
    setSel('q11', s.community.csc); setSel('q8', s.community.envHistoric);
    setVal('f-lead-agency', s.lead);
    setSel('f-timeline', s.time, '— Not set —');
    setVal('f-funding', s.funding);
    setVal('f-partners', s.partners);
    setVal('f-mechanism', s.mechanism);
    setSel('f-hazard-1', s.hazards[0], '— Not set —');
    setSel('f-hazard-2', s.hazards[1], '—');
    setSel('f-hazard-3', s.hazards[2], '—');
    setSel('f-action-type', s.types[0], '— Not set —');
    // associated risk environment checkboxes, DOM order = data order
    var assocLabels = ['Transportation', 'Energy', 'Water infrastructure', 'Communications infrastructure & systems', 'Buildings', 'Direct community engagement'];
    var assocBoxes = [];
    document.querySelectorAll('[data-dms="section"][data-name="key-facts"] input[type="checkbox"]').forEach(function (b) { assocBoxes.push(b); });
    assocBoxes.forEach(function (box, i) { box.checked = s.assocRisk.indexOf(assocLabels[i]) >= 0; });
    setVal('f-local-priority', s.jp);
    setSel('f-county-priority', s.countyPriority, '— Not set —');
    // readiness / maturity stay Not Yet Assessed — the fields don't exist in the data yet
    setSel('q1', s.flags.critical); setSel('q3', s.flags.buyout);
    setSel('q2', s.flags.culvert); setSel('q4', s.flags.generator);
    setSel('q7', s.flags.rlsrl);
    setVal('f-geom', s.geometry);
    setVal('f-address', s.address);
    setVal('f-action-number', s.actionNumber);
    setVal('f-created', s.created);
    setSel('f-source', s.planSource);
    setSel('f-in-last-hmp', s.lastHmp, '— Not answered —');
    setVal('f-poc', s.poc);
    setVal('f-poc-title', s.pocTitle);
    setVal('f-poc-email', s.pocEmail);
    setVal('f-status-details', s.statusDetails);

    var bar = q('savebar-title');
    if (bar) bar.textContent = (s.jurisdiction || placeName(s)) + ' | ' + (s.title || 'Untitled action');
    var cc = q('crumb-county'), cj = q('crumb-jur'), pid = q('page-id');
    if (cc) cc.textContent = (s.county ? (s.county === 'New York City' ? 'New York City' : s.county + ' County') : 'New York State') + ' Actions';
    if (cj) cj.textContent = s.jurisdiction || (s.scope === 'State' ? 'Statewide' : placeName(s));
    if (pid) pid.textContent = 'Action id ' + s.id + ' · editing draft · not saved';
    document.title = 'MitigateNY — Action Edit (' + (s.title || 'Untitled action') + ')';
  }

  // ── the widget panel ───────────────────────────────────────────────────────
  var current = Number(sessionStorage.getItem(KEY)) || DEFAULT_ID;
  if (!SPECIMENS.some(function (s) { return s.id === current; })) current = DEFAULT_ID;

  function pick(id) {
    if (id === DEFAULT_ID) sessionStorage.removeItem(KEY);
    else sessionStorage.setItem(KEY, String(id));
    location.reload();
  }

  var panel = document.createElement('div');
  panel.id = 'specimenWidget';
  panel.style.cssText = 'position:fixed;top:0;right:0;z-index:70;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;';
  var rows = SPECIMENS.map(function (s, i) {
    var pct = Math.round(100 * s.fill / s.fillMax);
    var isCur = s.id === current;
    return '<button data-sid="' + s.id + '" style="display:block;width:100%;text-align:left;padding:7px 10px;border:0;border-top:1px solid #2e4152;cursor:pointer;background:' + (isCur ? '#3d2f14' : 'transparent') + ';" ' +
      'onmouseover="this.style.background=\'' + (isCur ? '#4a3915' : '#22303c') + '\'" onmouseout="this.style.background=\'' + (isCur ? '#3d2f14' : 'transparent') + '\'">' +
      '<span style="display:flex;justify-content:space-between;gap:8px;align-items:baseline;">' +
        '<span style="font-size:11px;color:' + (isCur ? '#EAAD43' : '#dbe7ee') + ';white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:250px;">' + (i + 1) + ' · ' + esc(s.title || '(no name)') + '</span>' +
        '<span style="font-size:10px;color:#7d97a8;white-space:nowrap;">' + s.fill + '/' + s.fillMax + '</span>' +
      '</span>' +
      '<span style="display:block;font-size:10px;color:#7d97a8;margin-top:1px;">' + esc(s.county || 'Statewide') + ' · ' + esc(s.status || 'no status') + '</span>' +
      '<span style="display:block;height:3px;background:#22303c;border-radius:2px;margin-top:4px;"><span style="display:block;height:3px;width:' + pct + '%;background:' + (pct > 60 ? '#54B99B' : pct > 25 ? '#EAAD43' : '#DD524C') + ';border-radius:2px;"></span></span>' +
      '</button>';
  }).join('');
  var cur = SPECIMENS.filter(function (s) { return s.id === current; })[0] || {};
  panel.innerHTML =
    '<div style="background:#16222c;border:1px solid #EAAD43;border-top:0;border-right:0;border-radius:0 0 0 10px;box-shadow:0 6px 24px rgba(0,0,0,.45);max-width:300px;">' +
      '<button id="spwToggle" style="display:block;width:100%;background:transparent;border:0;cursor:pointer;padding:8px 10px 7px;text-align:left;">' +
        '<span style="display:block;font-size:9px;letter-spacing:.14em;color:#EAAD43;">SPECIMEN SWITCHER — REVIEW WIDGET</span>' +
        '<span style="display:block;font-size:10px;color:#7d97a8;margin-top:2px;">not part of the design · 10 real actions · <span style="color:#dbe7ee">' + esc((cur.title || '(no name)').slice(0, 26)) + '</span></span>' +
      '</button>' +
      '<div id="spwList" style="display:none;max-height:70vh;overflow-y:auto;">' + rows +
        '<div style="padding:7px 10px;border-top:1px solid #2e4152;font-size:9px;color:#7d97a8;line-height:1.5;">Real records from Actions Cleaned (source 12453 / view 13192). Selection persists between the view and edit pages.</div>' +
      '</div>' +
    '</div>';
  document.body.appendChild(panel);
  document.getElementById('spwToggle').addEventListener('click', function () {
    var list = document.getElementById('spwList');
    list.style.display = list.style.display === 'none' ? 'block' : 'none';
  });
  panel.querySelectorAll('button[data-sid]').forEach(function (b) {
    b.addEventListener('click', function () { pick(Number(b.getAttribute('data-sid'))); });
  });

  // ── apply on load (the default specimen keeps the hand-authored markup) ────
  if (current !== DEFAULT_ID) {
    var spec = SPECIMENS.filter(function (s) { return s.id === current; })[0];
    try {
      if (IS_EDIT) renderEdit(spec); else renderView(spec);
    } catch (e) {
      console.error('[specimen-widget] render failed:', e);
    }
  }
})();
