import fs from 'fs';
const spec=[];
const S=(id,blocks)=>spec.push({id,blocks});

// ===== People & Communities =====
// Local Context #0 — county profile
S("2271041",[
{t:"h",text:`Location and Geography`,tag:"h3"},
{t:"p",text:`The County’s geographical location exposes it to a wide range of natural hazards. The City of Schenectady, five towns, and two villages comprise the municipalities in the County. The densest residential, commercial, and industrial development is in the City of Schenectady, with suburban uses clustered in the Village of Scotia, Towns of Glenville, Niskayuna, and Rotterdam. The Towns of Duanesburg and Princetown are primarily rural in character although there are small commercial centers in the Village of Delanson and the Town of Duanesburg.`},
{t:"p",text:`Schenectady County occupies approximately 208 square miles, of which 3.5 square miles is water area. It is the second smallest of the 57 counties outside of New York City. The County is located in the eastern center of the State of New York about halfway between NYC and Montreal. The County is bordered to the northeast by Saratoga County, to the northwest by Montgomery County, to the southwest by Schoharie County and to the south by Albany County and is bisected by the Mohawk River. A line across the county, in its widest part, would be drawn from the south-east corner of Niskayuna to a point on the Schoharie Creek, near the south-west corner of Duanesburg and would be about 28 miles long. The Mohawk River flows in a general south-easterly direction through the county and forms a part of its north-eastern border. Besides this river, the principal streams are Schoharie Creek, Norman's Kill, and their tributaries.`},
{t:"p",text:`The Adirondack Mountains are to the north of the County and the Helderberg Escarpment and Catskill Mountains are located to the south. The Mohawk River traverses the County from the northwest corner to the southeast corner. Variation in elevation is significant across the County. Lands adjacent to the Mohawk River are nearly level. Elevation ranges from 200 feet on the Mohawk River to a high of 1,435 feet in the west-central part of the County. Prime agricultural soils are predominantly located on flat lands along the Mohawk River and Schoharie Creek. Additional concentrations of prime soils are found in westernmost Glenville along the Montgomery County line and along the Normanskill in Princetown.`},
{t:"h",text:`Brief History`,tag:"h3"},
{t:"p",text:`Founded as a Dutch settlement in 1662, it took its name from the nearby Mohawk village of Schaunactada, probably meaning “over,” or “across the pine plains.” In 1690 the village was virtually destroyed in the Schenectady Massacre by the French and Indians. With an influx of English settlers in the early 1700s the site (above a series of waterfalls) was fortified and developed as the terminus of the portage between Albany, on the Hudson, and the Mohawk. The prosperous transshipment business declined after 1825 with the opening of the Erie Canal. Economic recovery for the city was stimulated by the arrival of the Mohawk and Hudson Railroad in 1831 and the establishment of a locomotive works in 1848.`},
{t:"p",text:`In 1886 the Edison Machine Works were moved from New York City to Schenectady, and by a series of mergers in 1892 the General Electric Company was created with its main administrative offices in the city. Later, plants manufacturing a wide range of electrical equipment and experimental laboratories, eventually including nuclear research centers, were established. Chemicals are also manufactured. Union College of Union University was founded (1795) in Schenectady and includes the 16-sided Nott Memorial building and Jackson’s Garden on its 100-acre (40-hectare) campus. Schenectady County Community College of the State University of New York system was established in 1967. The city’s colonial past survives in its downtown Historic Stockade area.`},
{t:"h",text:`Major Industries (Economic Drivers) and Notable Infrastructure`,tag:"h3"},
{t:"p",text:`Schenectady County is considered an industrial and research center with a strong concentration of manufacturing and research performed by General Electric (GE), GE Research and Development - Global Research, the Stratton Air National Guard Base, MVP Healthcare, Ellis Hospital System, Knolls Atomic Power Laboratory (KAPL), the SI Group, and Golub Corporation. Notable infrastructure within the County includes 5 major bridges crossing the Mohawk River, 14 water and wastewater systems, 16 National Grid Electrical Sub Stations, 3 hospitals, nursing homes, a rehabilitation center, and three colleges (Schenectady County Community College, Union College, and the Clarkson University Capital Region Campus). Additionally major roadways (including the NYS Thruway), passenger and freight rail, and the New York State Canal System traverse through the County. Rivers Casino Resort is a large employer in the County.`},
{t:"p",text:`Schenectady boasts its own symphony and Proctors Theater brings off-Broadway productions to Upstate New York. Schenectady County also has an airport located in the Town of Glenville. The Schenectady County Airport is home to the 109th New York Air National Guard Airlift Wing at Stratton Air National Guard Base. Private and Air National Guard aircraft use the airport’s three runways, which are 7000, 4840 and 2639 feet long.`},
{t:"h",text:`Climate`,tag:"h3"},
{t:"p",text:`In most seasons the coldest temperature ranges from 5 degrees F to 15 degrees F. Summers are warm with temperatures of 90 degrees F or higher occurring on an average of 8 to 12 days per year, mostly between early June and late August. Average daytime temperatures in summer range from the upper 70’s to mid 80’s. The freeze-free season is approximately 165 days. The last freezing temperature in spring generally occurs between May 10 and 15 and the first freeze in fall occur around October 10. Annual precipitation averages 35 to 38 inches throughout most of the County. Snowfall averages 60 inches per season. Rainfall during the May to September growing season varies from 17 to 19 inches.`}
]);

// Governance Structure
S("2266842",[
{t:"p",text:`Schenectady County government is composed of 15 District Representatives members, one of which acts as the Chair of the Legislature.`}
]);

// Local Populations at Highest Risk — Social Vulnerability
S("2266833",[
{t:"p",text:`Social vulnerability is a broad concept examining the differential impact of hazards on society based on the existing socio-demographic conditions and community characteristics. The number of natural hazard events and disasters in the U.S. has been increasing, a trend that is expected to continue. The CDC's Division of Environmental Hazards and Health Effects defines social vulnerability in terms of the characteristics of a person or group that affect “their capacity to anticipate, cope with, resist, and recover from the impact” of a discrete and identifiable disaster in nature or society. A person’s vulnerability to disaster is influenced by many factors. The following six categories are among the most commonly accepted: socioeconomic status, age, gender, race and ethnicity, English language proficiency, and medical issues and disability. Many people may fit more than one category.`},
{t:"p",text:`At-risk groups, also referred to as socially vulnerable populations, require special attention in emergency management and planning since they are disproportionately affected by hazard events and natural disasters. Lower-income populations and communities of color are more often concentrated in areas that expose them to climate-related health threats and those of lower socioeconomic status often have pre-existing vulnerabilities that may be exacerbated by the changing climate (e.g. underlying health conditions, inferior public infrastructure, limited access to healthcare, etc.)`},
{t:"p",text:`These patterns, where the burdens of hazard and climate-related impacts are disproportionately borne by low-income populations and communities of color, violate principles of environmental justice. The inequities must be addressed through targeted policies and actions. At the state level, The New York Climate Leadership and Community Protection Act (CLCPA), which was passed in 2019, takes an important step in the right direction by creating a Climate Justice Working Group and setting a target for disadvantaged communities to receive 40% (and no less than 35%) of the benefits from all New York State climate programs. However, there are many more actions that can be taken on the local scale to combat hazard and climate related inequalities. (Climate Vulnerability and Adaptation Report for the City of Schenectady)`},
{t:"p",text:`The Mitigation phase of emergency management involves developing policies to reduce risks to people and property during a disaster. This planning process sought to identify and collect information about vulnerable community members across Schenectady County and any on-going activities that provide services and resources to these individuals and groups before, during or after natural hazard events and/or disasters. As new policies and investments around environmental initiatives arise, it is critical for the local government to engage with its residents and businesses to ensure that climate related vulnerabilities are lessened equitably.`},
{t:"p",text:`Many Schenectady County Hazard Mitigation Plan Survey respondents identified senior citizens and the elderly as particularly vulnerable to hazard impacts. Many respondents indicated a need for direct outreach to elderly community members before, during and after hazard events.`},
{t:"p",text:`Several survey respondents from Niskayuna commented on risk to the elderly and other vulnerable community members and called for further assistance for these populations. Comments included:`},
{t:"ul",items:[
`“The elderly (who cannot shovel or plow for themselves) and the homeless. A team to check on the elderly during storms and a team to assist the homeless in finding a safe place to stay before a storm or drop in temperature.”`,
`“Seniors or those with disabilities are more prone to heat strokes and needing help in general. I am not sure how to help other than being neighborly.”`,
`“The town should develop a spreadsheet identifying elderly or special needs and develop a program to assist in emergency or serious weather events.”`,
`“Power outages for any reason can be problematic for older people living alone.”`,
`“Senior citizens should be prioritized for power outage response and fire departments help with flooded basements.”`,
`“The elderly and the homeless are most at risk from any natural disasters as they potentially either lack the capacity to handle extreme situations or are isolated from even asking for services. The homeless are constantly at risk from the natural elements.”`,
`“Our area has several nursing homes. Thinking back to Hurricane Katrina in Louisiana, this population had a very difficult time evacuating when the area was flooded.”`,
`“The elderly and homebound: in-person contact to reassure and advise them.”`,
`“Senior citizens; risk of not getting alerts due to lack of technology, hearing impaired. Mobility & transportation issues if evacuation needed.”`,
`“The elderly and those who live alone are particularly at risk. They need additional assistance to remove snow and a network that checks on their well being.”`,
`“Any seniors that are not able to get out and about due to the ice conditions.”`,
`“Elderly during a storm. People who can’t clear their driveway or car in a bad snowstorm. Perhaps there could be a service available for those that need it.”`,
`“Usually the elderly are the most vulnerable. Currently there is no help mechanism available to help this group other than neighbors.”`,
`“Aged and the disabled. Establish a system to check on them or evacuate them during critically dangerous times.”`,
`“People who live alone or who have a disability. A system where people could sign up to be on a list kept by the local health department or some other county/town department to be checked on in case of a weather emergency.”`,
`“Senior and health impaired persons would be vulnerable to many hazard conditions. Perhaps a registry would help. Otherwise they have to depend on relatives and neighbors.”`]},
{t:"p",text:`Several survey respondents from Scotia commented on risk to the elderly and other vulnerable community members and called for further assistance for these populations. Comments included:`},
{t:"ul",items:[
`“The elderly who need help with snow and ice removal and tree damage from storms.”`,
`“We have many seniors in my neighborhood. Emergency shelters would be helpful if their homes became unlivable or too dangerous for habitation.”`,
`“Home-bound seniors or people with disabilities, people who live alone would be vulnerable. Not everyone uses a computer, so mailings with guidelines on how to handle certain crises or TV messages to alert people would benefit. Teams of people that would be trained to contact people in their area to check on people or to warn people of impending problems and to check on them once an event is imminent or once it happens.”`,
`“In Scotia there is a large population of seniors. Continuing tv, radio and internet warning would help these people.”`,
`“Elderly people and others who rely on oxygen and other medical devices that require electricity.”`,
`“A community phone tree to check on vulnerable people. A voluntary sign up list of people who might qualify.”`,
`“Our seniors that still live in their houses. Better communication for them other than digital. So many do not have internet or computers.”`,
`“Any seniors in our community or people alone with disabilities, including mental disabilities, should be contacted during these times. I would be happy to help and get them the things they need.”`,
`“We have a large senior citizen population with limited income and family and friends. If you belong to the senior center, they have been calling people to see what they need, etc. They have meals on wheels, transportation available, and pick up meals. Not sure what could be done for seniors who need mechanical services, etc. done on their houses. We have GREAT police and fire services.”`,
`“Scotia is home to an aging population, so there are many people who are at risk.”`,
`“Some of our elderly or financially challenged would be especially vulnerable in times of severe heat/cold. These people would need a place to go and services to support them while there.”`,
`“Scotia has a significant elderly population. Having a list (voluntary) of those people may help first responders or citizen volunteers in assisting or checking on those people.”`,
`“The elderly people are extremely vulnerable to the power outages. Several neighbors are on oxygen and worry constantly about losing power for an extended period of time.”`,
`“Access to affordable generators, help using it correctly, neighbors or other responders having a list of these higher risk people and areas to check on them before, during, after. Forum to educate various people about available resources. Help during huge snowstorms to help dig people out of their house, clear cars and driveways etc.”`]},
{t:"p",text:`Though fewer respondents from Rotterdam, Delanson, Duanesburg and Glenville were represented, those who participated also highlighted the vulnerability of elderly members of their communities.`},
{t:"p",text:`A survey respondent from Duanesburg stated: “Neighborhood alert system of knocking on doors or phone tree to specifically include the elderly. Rural communities fail to include residents that are not active in the local school system. Rural society omits those not active on the internet or daily motorists. The elderly are overlooked and too often omitted from a rural community's daily activities. This compromises their safety, health and security. Rural communities must educate and encourage residents to knock on doors and use the phone to check up on elderly neighbors before and after a crisis emergency.”`},
{t:"p",text:`A survey respondent from Glenville stated: ”Seniors and disabled are more at risk. Phone call lists would be great to have so that we can reach out to individuals/families to see what their needs are.”`}
]);

// ===== Built Environment =====
// Local Context #0 — built environment big picture
S("2266850",[
{t:"p",text:`The built environment can generally be described as the man-made or modified structures that provide people with living, working, and recreational spaces. The built environment includes existing structures, infrastructure systems, critical facilities, and cultural resources. Areas of future growth and development are also an important component when assessing the built environment.`},
{t:"p",text:`Throughout time, floods have altered the floodplain landscape. These areas are continuously shaped by the forces of water - either eroded or built up through deposit of sediment. In more recent history, the landscape has been altered by human development, affecting both the immediate floodplain and events downstream. Historically, people have been attracted to bodies of water as places for living, industry, commerce, and recreation. During the early settlement across the US locations near water provided necessary access to transportation, a water supply and water power. In addition, many of these areas had fertile soils, making them prime from agricultural uses. This pattern of development continued as communities grew and in recent decades development along waterways and shorelines has been spurred by the aesthetic and recreational values of these sites.`},
{t:"p",text:`The result of these trends in developing the built environment has been an increased level of damage and destruction wrought by the natural forces of flooding and other natural hazards. Urbanization alters flood dynamics, too. Storm sewers and more efficient ditches that come with urban drainage systems speed flood flows resulting in more runoff in the watershed that moves faster and increases flooding.`},
{t:"p",text:`Although all built assets may be affected by hazards, some are more vulnerable because of their physical characteristics, location in hazard prone areas or socioeconomic uses. With increasing frequency and intensity, disasters are devastating the built environment in unprecedented ways. Inventorying assets, estimating asset value and loss values for hazards with clearly defined areas of concern, and evaluating population density and land use trends provides the foundation for identifying and analyzing risk to the built environment. This information can also be used to support decisions regarding future development in vulnerable areas.`},
{t:"p",text:`Schenectady County is located in the Capital District of New York and is a mixture of hill towns and low lying cities and suburbs It is the second smallest County geographically in the State. The Mohawk River, which runs through the middle of the County, and the Schoharie Creek flood frequently (2018 Schenectady County CEPA).`},
{t:"h",text:`Local land use and planning decisions`,tag:"h3"},
{t:"p",text:`Land use is the characterization of land based on what can be built on it and what the land can be used for. Land use refers to the relationship between people and the land – more specifically, how the physical world is adapted, modified, or put to use for human purposes. This includes even the “non-use” of lands reserved as wilderness or protected from human impacts.`},
{t:"p",text:`Zoning is how the government regulates land use and it is implemented in a community to guide the type and intensity of development occurring within its borders. Zoning ordinances regulate the kinds of uses and density of development allowed in specific areas called zoning districts. Subdivision regulations dictate the ways in which land is partitioned into building lots. These regulations, including site plan review requirements, control development of the built environment. The regulation of land use can increase or reduce the exposure of residents to natural hazards. Land-use planning is largely a regulatory activity designed to guide public and private uses of land to achieve public purposes. As the primary tool for hazard mitigation at the community level, effective land-use planning is critically important in the management of environmental hazards.`},
{t:"p",text:`Generally, across Schenectady County, risk to the built environment is defined as the FEMA Flood Insurance Rate Maps designated 1% and .2% annual chance floodplain. The primary flood hazard impact area within the County is related to the Mohawk River floodplain; based in its flood history and the size of the watershed which it drains. There are over 300 properties with structures within the Mohawk River floodplain. Examples of areas that may experience widespread damage are the Stockade area of the City of Schenectady, Washington Avenue and Schonowee Avenue in Scotia, Alplaus in Glenville, Rotterdam Junction and the Schenectady County Community College in Rotterdam. Floodplains for the minor streams that are mapped within the County generally have very small watersheds, with drainage areas of less than 10 square miles. These minor streams have had less than 10 structures with repetitive loss damages.`}
]);

// Local Context #1 — critical buildings and infrastructure
S("2266866",[
{t:"p",text:`Community facilities are the buildings, land, equipment and activities provided on the public’s behalf by government and/or private organizations. These facilities are important components to the quality of life of a municipality. Critical Facilities are necessities for the health, safety, wellbeing, and stability of communities. FEMA defines a critical facility as one that provides services and functions essential to a community, especially during and after a disaster. Critical infrastructure systems are essential for life safety and economic viability and include transportation, power, communication, and water and wastewater systems.`},
{t:"p",text:`Many critical facilities depend on infrastructure to function. For example, hospitals need electricity, water, and sewer to continue helping patients. As with critical facilities, the continued operations of infrastructure systems during and following a disaster are key factors in the severity of impacts and the speed of recovery.`},
{t:"p",text:`Typical critical facilities include hospitals, fire stations, police stations, storage of critical records, and similar facilities and critical infrastructure systems are depended upon for life safety and economic viability and include transportation, power, communication, and water and wastewater systems. These facilities should be given special consideration when formulating regulatory alternatives and floodplain management plans.`},
{t:"p",text:`Identifying critical facilities and infrastructure located in the floodplain in order to develop strategies to protect these facilities from the impacts of flood events is an important outcome of hazard mitigation planning. A critical facility should not be located in a floodplain if at all possible. For some activities and facilities, even a slight chance of flooding is too great a threat. New York Department of Environmental Conservation (DEC) Statute 6 CRR-NY 502.4 sets forth floodplain management criteria for State projects located in flood hazard areas. The law states that no such project related to critical facilities shall be undertaken in a Special Flood Hazard Area (SFHA) unless constructed according to specific mitigation specifications, including being raised 2’ above the Base Flood Elevation (BFE). In assessing vulnerabilities each jurisdiction has identified exposure to hazards, including all critical facilities/infrastructure in the 1% and .2% annual chance floodplain (Special Flood Hazard Area).`},
{t:"p",text:`The County is home to General Electric (GE), GE Research and Development Global Research, the Stratton Air National Guard Base, MVP Healthcare, Ellis Hospital System, Knolls Atomic Power Laboratory (KAPL), the SI Group, and Golub Corporation. Notable infrastructure within the County includes 5 major bridges crossing the Mohawk River, 14 water and wastewater systems, 16 National Grid Electrical Sub Stations, 3 hospitals, nursing homes, a rehabilitation center, and three colleges (Schenectady County Community College, Union College, and the Clarkson University Capital Region Campus). Additionally major roadways (including the Thruway), passenger and freight rail, and the New York State Canal System traverse through the County. Rivers Casino Resort is a large employer in the County.`}
]);

// ===== Natural Environment =====
// Local Context #0
S("2266764",[
{t:"p",text:`Environmental assets and natural resources are important to community identity and quality of life and support the economy through agriculture, tourism and recreation, and a variety of other ecosystem services, such as clean air and water. The natural environment also provides protective functions that reduce hazard impacts and increase resiliency. For instance, wetlands and riparian areas help absorb flood waters, soils and landscaping contribute to stormwater management, and vegetation provides erosion control and reduces runoff. Conservation of environmental assets may present opportunities to meet mitigation and other community objectives, such as protecting sensitive habitat, developing parks and trails, or contributing to the economy (Beyond the Basics).`}
]);

// Water Quality — Mohawk River, Normans Kill, Great Flats Aquifer
S("2266785",[
{t:"h",text:`The Mohawk River`,tag:"h3"},
{t:"p",text:`The Mohawk River is the principal water surface feature in the County. The flow of the river, part of the New York State Barge Canal System, is regulated by a series of locks. The river is Class A Regulated for fresh surface water under DEC water quality regulations and is considered a water source, recreation and a fish breeding and survival environment.`},
{t:"p",text:`Since the early twentieth century, when the state’s original canal system was significantly enlarged, the Mohawk River channel replaced many sections of the original Erie Canal. The navigable section of the Mohawk River covers approximately 70 miles from Little Falls, NY to the confluence with the Hudson River at Waterford, NY. The Mohawk River is currently more recreation-oriented than transportation- or cargo-oriented. It serves as a connector between the Hudson River and the Oswego Canal/Lake Ontario, Cayuga and Seneca Lakes. At its eastern terminus in Waterford, the Mohawk River joins the Hudson River forming a waterway that allows inland navigation from New York City to the Great Lakes.`},
{t:"h",text:`The Normans Kill`,tag:"h3"},
{t:"p",text:`Headwaters of the Normans Kill are found in the Town of Duanesburg. The stream then meanders in an east to southeasterly direction through most of Schenectady County. The Normans Kill is a DEC Class A fresh surface water and is an important waterbody because it flows in the Watervliet Reservoir which supplies drinking water to Albany County Residents.`},
{t:"h",text:`The Great Flats Aquifer`,tag:"h3"},
{t:"p",text:`The Great Flats, or the Schenectady Aquifer, is a unique groundwater resource and is one of the most productive aquifers in New York State. The Great Flats Aquifer serves as a reliable source of high quality drinking water for nearly 150,000 residents of both Schenectady and Saratoga Counties. On an average day, approximately 25 million gallons of water are withdrawn from the aquifer by the five Schenectady County municipalities: City of Schenectady, Village of Scotia, Town of Glenville, Town of Niskayuna, Town of Rotterdam.`},
{t:"p",text:`In Schenectady County, the Great Flats or Schenectady Aquifer, runs along the Mohawk Valley in silt, sand and gravel deposits. The aquifer serves most of Schenectady County and is approximately 14 miles long and underlies approximately 25 square miles in the Lower Mohawk River Basin in Schenectady County. It is approximately ½ mile wide at its western end and more than 5 miles wide when it reaches the City of Schenectady to the east.`},
{t:"p",text:`Several hydrogeologic studies have been conducted to define the characteristics of the aquifer. Based upon these findings, four zones have been established to provide the necessary degree of protection to the aquifer. The hydrogeologic characteristics of the four protection zones determine the appropriate land use activities permitted in each zone. Zone I carries the most stringent standards and Zone IV is the least restrictive. Protection zones for the wellfields in the Town of Rotterman (including the hamlet of Rotterdam Junction), City of Schenectady, Village of Scotia and Town of Glenville have all been delineated.`},
{t:"ul",items:[
`Zone I: Wellhead Protection Zone`,
`Zone II: Primary Recharge Zone`,
`Zone III: General Aquifer Recharge Zone`,
`Zone IV: Tributary Watershed Zone`]},
{t:"p",text:`The Town of Rotterdam, City of Schenectady, Village of Scotia and Town of Glenville (the Schenectady County municipalities drawing water from the aquifer) have adopted a set of uniform rules to protect the aquifer. These rules, known as the Schenectady County Intermunicipal Watershed Rules and Regulations, provide a comprehensive set of land use controls and prohibitions designed to prevent contamination of the aquifer. They influence the types and intensity of development within the defined protection zones.`}
]);

fs.writeFileSync(new URL('../edits/chapters1.json',import.meta.url), JSON.stringify(spec,null,1));
console.log('wrote chapters1.json with',spec.length,'slots');
